M48
; DRILL file {KiCad 9.0.1} date 2026-01-20T22:12:47+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-20T22:12:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X85.185Y-65.017
X85.185Y-143.287
X202.235Y-65.017
X202.235Y-143.287
M30
